import type { Metadata } from "next";
import { ChakraProviders } from "@/lib/chakra/provider/ChakraProvider";
import { spaceMono, workSans } from "@/public/fonts/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${workSans.variable} ${spaceMono.variable}`}>
      <body>
        <ChakraProviders>{children}</ChakraProviders>
      </body>
    </html>
  );
}
